import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import FloatingWhatsApp from "@/components/shared/FloatingWhatsApp";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es"   className={`${poppins.variable} ${inter.variable}`}
>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-[var(--font-body)]`}
      >
        <div className="min-h-screen bg-background">
      <Header />
        {children}
        <FloatingWhatsApp />
        <Footer />
      </div>
      </body>
    </html>
  );
}
